import { supabase } from "@/integrations/supabase/client";

interface BackorderItem {
  productId: string;
  productName: string;
  quantity: number;
  unitPrice: number;
}

export async function moveItemsToBackorder(
  orderId: string,
  selectedItems: BackorderItem[]
) {
  try {
    // Fetch the original order
    const { data: originalOrder, error: fetchError } = await supabase
      .from("orders")
      .select("*")
      .eq("id", orderId)
      .single();

    if (fetchError || !originalOrder) {
      throw new Error("Failed to fetch original order");
    }

    const originalProducts: any[] = Array.isArray(originalOrder.products)
      ? originalOrder.products
      : [originalOrder.products];

    // Build backorder products and update original products
    const backorderProducts: any[] = [];
    const updatedOriginalProducts: any[] = [];

    for (const product of originalProducts) {
      const selectedItem = selectedItems.find(
        (item) => item.productId === (product.id || product.product_id)
      );

      if (selectedItem) {
        const originalQty = Number(product.quantity || 1);
        const moveQty = selectedItem.quantity;

        // Add to backorder
        backorderProducts.push({
          ...product,
          quantity: moveQty,
          total_price: selectedItem.unitPrice * moveQty,
        });

        // If partial quantity remains, keep in original
        if (originalQty > moveQty) {
          updatedOriginalProducts.push({
            ...product,
            quantity: originalQty - moveQty,
            total_price: selectedItem.unitPrice * (originalQty - moveQty),
          });
        }
        // If all quantity moved, don't add to updated products
      } else {
        // Not selected — keep in original
        updatedOriginalProducts.push(product);
      }
    }

    if (backorderProducts.length === 0) {
      throw new Error("No items selected for backorder");
    }

    // Calculate new totals for original order
    const newOriginalSubtotal = updatedOriginalProducts.reduce(
      (sum: number, p: any) => sum + Number(p.total_price || p.price * (p.quantity || 1)),
      0
    );

    // Calculate backorder totals
    const backorderSubtotal = backorderProducts.reduce(
      (sum: number, p: any) => sum + Number(p.total_price || p.price * (p.quantity || 1)),
      0
    );

    // Determine the next split number
    const { data: existingSplits } = await supabase
      .from("orders")
      .select("split_number")
      .eq("master_order_id", orderId)
      .order("split_number", { ascending: false })
      .limit(1);

    const nextSplitNumber = existingSplits && existingSplits.length > 0
      ? (existingSplits[0].split_number || 0) + 1
      : 1;

    // Create the backorder
    const backorderData = {
      order_number: "", // Auto-generated by trigger
      customer_id: originalOrder.customer_id,
      customer_name: originalOrder.customer_name,
      customer_phone: originalOrder.customer_phone,
      customer_address: originalOrder.customer_address,
      delivery_address: originalOrder.delivery_address,
      same_as_billing: originalOrder.same_as_billing,
      delivery_suburb_id: originalOrder.delivery_suburb_id,
      contact_id: originalOrder.contact_id,
      contact_name: originalOrder.contact_name,
      contact_email: originalOrder.contact_email,
      contact_phone: originalOrder.contact_phone,
      products: backorderProducts,
      subtotal: backorderSubtotal,
      adjustments: 0,
      delivery_fee: 0,
      total_amount: backorderSubtotal,
      delivery_method: originalOrder.delivery_method,
      delivery_date: null,
      delivery_time: null,
      admin_id: originalOrder.admin_id,
      order_notes: originalOrder.order_notes,
      delivery_notes: originalOrder.delivery_notes,
      purchase_order: originalOrder.purchase_order,
      payment_method: originalOrder.payment_method,
      status: "back_order" as const,
      is_split_order: true,
      master_order_id: orderId,
      split_number: nextSplitNumber,
      payment_status: "pending",
    };

    const { data: backorder, error: backorderError } = await supabase
      .from("orders")
      .insert(backorderData)
      .select()
      .single();

    if (backorderError) {
      throw new Error(`Failed to create backorder: ${backorderError.message}`);
    }

    // Update the original order
    if (updatedOriginalProducts.length === 0) {
      // All items moved — cancel original
      const { error: updateError } = await supabase
        .from("orders")
        .update({
          products: [],
          subtotal: 0,
          total_amount: Number(originalOrder.delivery_fee || 0),
          status: "cancelled" as const,
        })
        .eq("id", orderId);

      if (updateError) {
        throw new Error(`Failed to update original order: ${updateError.message}`);
      }
    } else {
      // Recalculate original order total
      const newTotal = newOriginalSubtotal + Number(originalOrder.delivery_fee || 0) + Number(originalOrder.adjustments || 0);

      const { error: updateError } = await supabase
        .from("orders")
        .update({
          products: updatedOriginalProducts,
          subtotal: newOriginalSubtotal,
          total_amount: newTotal,
        })
        .eq("id", orderId);

      if (updateError) {
        throw new Error(`Failed to update original order: ${updateError.message}`);
      }
    }

    return {
      backorderNumber: backorder.order_number,
      backorderId: backorder.id,
      itemsMoved: backorderProducts.length,
    };
  } catch (error: any) {
    console.error("Error in moveItemsToBackorder:", error);
    throw error;
  }
}
