
import { supabase } from "@/integrations/supabase/client";
import { Customer, CartItem, SelectedContact } from "../types";
import { serializeCartItemsWithFormatting } from "./orderFormattingService";

// Interface for creating single orders
interface CreateSingleOrderParams {
  customer: Customer;
  selectedContact?: SelectedContact | null;
  cart: CartItem[];
  adjustments: number;
  deliveryMethod: "delivery" | "pickup";
  deliveryDate: string;
  deliveryTime: string;
  pickupTiming?: "now" | "scheduled";
  specialInstructions: string;
  paymentMethod: string;
  orderNotes: string;
  deliveryNotes: string;
  purchaseOrder: string;
  deliveryAddress: string;
  sameAsBilling: boolean;
  suburbId: string;
  orderTotals: any;
}

// Interface for creating split orders (simplified)
interface CreateSplitOrderParams {
  customer: Customer;
  selectedContact?: SelectedContact | null;
  cart: CartItem[];
  adjustments: number;
  deliveryMethod: "delivery" | "pickup";
  pickupTiming?: "now" | "scheduled";
  splits: any[];
  paymentMethod: string;
  specialInstructions: string;
  orderNotes: string;
  deliveryNotes: string;
  purchaseOrder: string;
  orderTotals: any;
}

export async function createSingleOrder(params: CreateSingleOrderParams) {
  try {
    // Fetch current payment settings for calculations
    const { data: paymentSettings, error: settingsError } = await supabase
      .from('payment_settings')
      .select('*')
      .single();

    if (settingsError) {
      console.error('Error fetching payment settings:', settingsError);
      throw new Error(`Failed to fetch payment settings: ${settingsError.message}`);
    }

    if (!paymentSettings) {
      throw new Error('Payment settings not found. Please configure payment settings first.');
    }

    // Serialize cart items for database storage - the trigger will automatically create products_formatted
    const serializedProducts = serializeCartItemsWithFormatting(params.cart);

    // Determine order status based on delivery method and pickup timing
    let orderStatus: 'back_order' | 'requested' | 'delivered' = 'requested';
    
    if (params.deliveryMethod === 'pickup') {
      if (params.pickupTiming === 'now') {
        // Immediate pickup orders go straight to delivered
        orderStatus = 'delivered';
      } else {
        // Scheduled pickup orders go to back_order (On Hold)
        orderStatus = 'back_order';
      }
    } else {
      // For delivery orders, check stock availability
      const { data: statusResult, error: statusError } = await supabase
        .rpc('determine_order_status', { order_items: serializedProducts });
      
      if (statusError) {
        console.warn('Error determining order status, defaulting to requested:', statusError);
        orderStatus = 'requested';
      } else {
        // Map the database function result to our allowed statuses
        orderStatus = (statusResult === 'back_order') ? 'back_order' : 'requested';
      }
    }

    const pickupAddress = import.meta.env.VITE_PICKUP_ADDRESS || 'Pickup from yard';
    const isPickup = params.deliveryMethod === 'pickup';
    const customerAddress = isPickup
      ? pickupAddress
      : (params.sameAsBilling ? params.customer.full_address : params.deliveryAddress);
    const deliveryAddress = isPickup
      ? pickupAddress
      : (params.sameAsBilling ? params.customer.full_address : params.deliveryAddress);
    const sameAsBilling = isPickup ? true : params.sameAsBilling;
    const deliverySuburbId = isPickup ? null : (params.suburbId || null);

    const orderData = {
      order_number: '', // Will be auto-generated by database trigger
      customer_id: params.customer.id,
      customer_name: `${params.customer.first_name} ${params.customer.last_name}`,
      customer_phone: params.customer.phone,
      customer_address: customerAddress,
      delivery_address: deliveryAddress,
      same_as_billing: sameAsBilling,
      delivery_suburb_id: deliverySuburbId,
      contact_id: params.selectedContact?.id || null,
      contact_name: params.selectedContact?.name || null,
      contact_email: params.selectedContact?.email || null,
      contact_phone: params.selectedContact?.phone || null,
      products: serializedProducts,
      subtotal: params.orderTotals.subtotal,
      adjustments: params.orderTotals.adjustments,
      delivery_fee: params.orderTotals.deliveryFee,
      total_amount: params.orderTotals.totalAmount,
      delivery_method: params.deliveryMethod,
      delivery_date: params.deliveryDate || null,
      delivery_time: params.deliveryTime || null,
      truck_type: null,
      truck_id: null,
      driver_id: null,
      special_instructions: params.specialInstructions,
      order_notes: params.orderNotes,
      delivery_notes: params.deliveryNotes,
      purchase_order: params.purchaseOrder,
      payment_method: params.paymentMethod,
      status: orderStatus,
      is_split_order: false,
      payment_status: 'pending'
      // Note: driver_name, truck_registration, truck_type_display will be automatically populated by the database trigger
    };

    console.log('Creating single order with data:', orderData);

    const { data: order, error } = await supabase
      .from('orders')
      .insert(orderData)
      .select()
      .single();

    if (error) {
      console.error('Error creating order:', error);
      throw new Error(`Failed to create order: ${error.message}`);
    }

    console.log('Single order created successfully:', order);

    return {
      type: 'single' as const,
      orderNumber: order.order_number,
      orderId: order.id
    };
  } catch (error: any) {
    console.error('Error in createSingleOrder:', error);
    throw new Error(error.message || 'Failed to create single order');
  }
}

export async function createSplitOrder(params: CreateSplitOrderParams) {
  try {
    // Fetch current payment settings for calculations
    const { data: paymentSettings, error: settingsError } = await supabase
      .from('payment_settings')
      .select('*')
      .single();

    if (settingsError) {
      console.error('Error fetching payment settings:', settingsError);
      throw new Error(`Failed to fetch payment settings: ${settingsError.message}`);
    }

    if (!paymentSettings) {
      throw new Error('Payment settings not found. Please configure payment settings first.');
    }

    const orders = [];

    // Serialize cart items for database storage
    const serializedProducts = serializeCartItemsWithFormatting(params.cart);

    // Determine master order status based on delivery method and pickup timing
    let masterOrderStatus: 'back_order' | 'requested' | 'delivered' = 'requested';
    
    if (params.deliveryMethod === 'pickup') {
      if (params.pickupTiming === 'now') {
        // Immediate pickup orders go straight to delivered
        masterOrderStatus = 'delivered';
      } else {
        // Scheduled pickup orders go to back_order (On Hold)
        masterOrderStatus = 'back_order';
      }
    } else {
      // For delivery orders, check stock availability
      const { data: statusResult, error: statusError } = await supabase
        .rpc('determine_order_status', { order_items: serializedProducts });
      
      if (statusError) {
        console.warn('Error determining master order status, defaulting to requested:', statusError);
        masterOrderStatus = 'requested';
      } else {
        // Map the database function result to our allowed statuses
        masterOrderStatus = (statusResult === 'back_order') ? 'back_order' : 'requested';
      }
    }

    // Create master order entry - this is a summary record
    const pickupAddress = import.meta.env.VITE_PICKUP_ADDRESS || 'Pickup from yard';
    const isPickup = params.deliveryMethod === 'pickup';
    
    // Use fallback strategy for master order address to prevent null constraint violations
    let masterCustomerAddress: string;
    let masterDeliveryAddress: string;
    
    if (isPickup) {
      masterCustomerAddress = pickupAddress;
      masterDeliveryAddress = pickupAddress;
    } else {
      // For delivery orders, use customer address as fallback, or first split's address
      const fallbackAddress = params.customer.full_address || 
                              (params.splits.length > 0 && !params.splits[0].sameAsBilling ? params.splits[0].deliveryAddress : null) ||
                              'Address to be confirmed';
      
      masterCustomerAddress = fallbackAddress;
      masterDeliveryAddress = fallbackAddress;
    }
    const masterSameAsBilling = true;
    const masterOrderData = {
      order_number: '', // Will be auto-generated by database trigger
      customer_id: params.customer.id,
      customer_name: `${params.customer.first_name} ${params.customer.last_name}`,
      customer_phone: params.customer.phone,
      customer_address: masterCustomerAddress,
      delivery_address: masterDeliveryAddress,
      same_as_billing: masterSameAsBilling,
      contact_id: params.selectedContact?.id || null,
      contact_name: params.selectedContact?.name || null,
      contact_email: params.selectedContact?.email || null,
      contact_phone: params.selectedContact?.phone || null,
      products: serializedProducts,
      subtotal: params.orderTotals.subtotal,
      adjustments: params.orderTotals.adjustments,
      delivery_fee: params.orderTotals.deliveryFee,
      total_amount: params.orderTotals.totalAmount,
      delivery_method: params.deliveryMethod,
      payment_method: params.paymentMethod,
      order_notes: params.orderNotes,
      delivery_notes: params.deliveryNotes,
      purchase_order: params.purchaseOrder,
      status: masterOrderStatus,
      is_split_order: false, // Master order is not a split order itself
      master_order_id: null,
      split_number: null,
      payment_status: 'pending',
      truck_type: null,
      truck_id: null,
      driver_id: null
    };

    const { data: masterOrder, error: masterError } = await supabase
      .from('orders')
      .insert(masterOrderData)
      .select()
      .single();

    if (masterError) {
      console.error('Error creating master order:', masterError);
      throw new Error(`Failed to create master order: ${masterError.message}`);
    }

    orders.push(masterOrder);

    // Create individual split orders
    for (let i = 0; i < params.splits.length; i++) {
      const split = params.splits[i];
      // Calculate split totals with decimal quantity support
      const splitSubtotal = split.products.reduce((sum: number, splitProduct: any) => {
        const cartItem = params.cart.find(cartItem => cartItem.product.id === splitProduct.productId);
        if (!cartItem) {
          console.error(`Product not found in cart: ${splitProduct.productId}`);
          return sum;
        }
        return sum + (cartItem.unit_price * parseFloat(splitProduct.quantity.toString()));
      }, 0);

      // Convert split products to match the expected format
      const splitProducts = split.products.map((splitProduct: any) => {
        const cartItem = params.cart.find(cartItem => cartItem.product.id === splitProduct.productId);
        if (!cartItem) {
          console.error(`Product not found in cart for split product: ${splitProduct.productId}`);
          return null;
        }
        return {
          id: cartItem.product.id,
          name: cartItem.product.name,
          price: cartItem.unit_price,
          quantity: parseFloat(splitProduct.quantity.toString()),
          total_price: cartItem.unit_price * parseFloat(splitProduct.quantity.toString())
        };
      }).filter(Boolean);

      // Determine split order status based on delivery method and pickup timing
      let splitOrderStatus: 'back_order' | 'requested' | 'delivered' = 'requested';
      
      if (params.deliveryMethod === 'pickup') {
        if (params.pickupTiming === 'now') {
          // Immediate pickup orders go straight to delivered
          splitOrderStatus = 'delivered';
        } else {
          // Scheduled pickup orders go to back_order (On Hold)
          splitOrderStatus = 'back_order';
        }
      } else {
        // For delivery orders, check stock availability of this split's products
        const { data: statusResult, error: statusError } = await supabase
          .rpc('determine_order_status', { order_items: splitProducts });
        
        if (statusError) {
          console.warn(`Error determining split order ${i + 1} status, defaulting to requested:`, statusError);
          splitOrderStatus = 'requested';
        } else {
          // Map the database function result to our allowed statuses
          splitOrderStatus = (statusResult === 'back_order') ? 'back_order' : 'requested';
        }
      }

      // Use fallback strategy for split addresses to prevent null constraint violations
      let splitCustomerAddress: string;
      let splitDeliveryAddress: string;
      
      if (isPickup) {
        splitCustomerAddress = pickupAddress;
        splitDeliveryAddress = pickupAddress;
      } else if (split.sameAsBilling) {
        const billingAddress = params.customer.full_address || 'Customer address to be confirmed';
        splitCustomerAddress = billingAddress;
        splitDeliveryAddress = billingAddress;
      } else {
        const customAddress = split.deliveryAddress || 'Delivery address to be confirmed';
        splitCustomerAddress = customAddress;
        splitDeliveryAddress = customAddress;
      }
      const splitSameAsBilling = isPickup ? true : split.sameAsBilling;
      const splitDeliverySuburbId = isPickup ? null : (split.sameAsBilling ? params.customer.suburb_id : (split.deliverySuburbId || split.suburbId));

      const splitOrderData = {
        order_number: '', // Will be auto-generated by database trigger
        customer_id: params.customer.id,
        customer_name: `${params.customer.first_name} ${params.customer.last_name}`,
        customer_phone: params.customer.phone,
        customer_address: splitCustomerAddress,
        delivery_address: splitDeliveryAddress,
        same_as_billing: splitSameAsBilling,
        delivery_suburb_id: splitDeliverySuburbId,
        contact_id: params.selectedContact?.id || null,
        contact_name: params.selectedContact?.name || null,
        contact_email: params.selectedContact?.email || null,
        contact_phone: params.selectedContact?.phone || null,
        products: splitProducts,
        subtotal: splitSubtotal,
        adjustments: 0,
        delivery_fee: split.deliveryFee || 0,
        total_amount: splitSubtotal + (split.deliveryFee || 0),
        delivery_method: params.deliveryMethod,
        delivery_date: split.deliveryDate,
        delivery_time: split.deliveryTime,
        truck_type: null,
        truck_id: null,
        driver_id: null,
        special_instructions: split.specialInstructions || '',
        order_notes: params.orderNotes,
        delivery_notes: params.deliveryNotes,
        purchase_order: params.purchaseOrder,
        payment_method: params.paymentMethod,
        status: splitOrderStatus,
        is_split_order: true,
        master_order_id: masterOrder.id,
        split_number: i + 1,
        payment_status: 'pending'
        // Note: driver_name, truck_registration, truck_type_display will be automatically populated by the database trigger
      };

      console.log(`Creating split order ${i + 1}:`, splitOrderData);

      const { data: splitOrder, error: splitError } = await supabase
        .from('orders')
        .insert(splitOrderData)
        .select()
        .single();

      if (splitError) {
        console.error(`Error creating split order ${i + 1}:`, splitError);
        throw new Error(`Failed to create split order ${i + 1}: ${splitError.message}`);
      }

      orders.push(splitOrder);
    }

    console.log('Split orders created successfully:', orders);

    return {
      type: 'split' as const,
      orderNumber: masterOrder.order_number,
      splitCount: params.splits.length,
      orders
    };
  } catch (error: any) {
    console.error('Error in createSplitOrder:', error);
    throw new Error(error.message || 'Failed to create split order');
  }
}
