
project_id = "wntcxbxitsanbyrtfhwv"

[functions.delete-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.generate-pdf-receipt]
verify_jwt = false

[functions.generate-thermal-receipt]
verify_jwt = false

[functions.order-export-webhook]
verify_jwt = false

[functions.sms-webhook]
verify_jwt = false

[functions.wc-sync]
verify_jwt = false

[functions.test-function]
verify_jwt = false
