// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wntcxbxitsanbyrtfhwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndudGN4YnhpdHNhbmJ5cnRmaHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDM2NTQsImV4cCI6MjA2NTIxOTY1NH0.lPHMb4tCdoVgIAG4G0FbLcnBcV-mhNIAc8UUuYbo91Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);